version: '3.8'
services:
  nginx:
    image: nginx:1.23.4
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "7000:80"
    volumes:
      - ./nginx/configs/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - frontend
      - backend
      - postgres
      - redis
    networks:
      - app-network
    env_file:
      - .env

  backend:
      build: ./BRAVO_BE
      container_name: backend
      restart: unless-stopped
      tty: true
      working_dir: /usr/app
      ports:
        - "7001:4000"
      volumes:
        - /app/node_modules
        - ./backend/src/:/app/
      depends_on:
        - postgres
        - redis 
      networks:
        - app-network
      env_file:
        - .env

  frontend:
      build: ./BRAVO_FE
      container_name: frontend
      restart: unless-stopped
      tty: true
      working_dir: /usr/app
      ports:
        - "7002:3000"
      volumes:
        - /app/node_modules
        - ./frontend/src/:/app/
      depends_on:
        - backend
      networks:
        - app-network
      env_file:
        - .env

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB_HOST=postgres
      - POSTGRES_DB_PORT=5432
      - POSTGRES_DB_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bravo_db
      - POSTGRES_DB_LOGGING=false
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "7432:5432"
    networks:
      - app-network
    env_file:
      - .env

  redis:
    image: redis
    container_name: redis
    environment:
      - REDIS_URL='redis://redis:6379'

    ports: 
    - "7379:6379"
    restart: always
    volumes:
      - /var/lib/redis/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
