name: SSH deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup SSH Keys
      uses: webfactory/ssh-agent@v0.4.0 # использование github action для настроек ssh-agent
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} # используйте приватный ключ SSH как секреты Github
      
    - name: SSH and clone repository
      run: git clone git@github.com:alexandrBally/BRAVO_DEVOPS.git # используйте ваши данные для подключения
