on:
    push:
      branches:
        - develop
    workflow_dispatch:
    
jobs:
    deploy_app:
      name: run pull
      runs-on: ubuntu-latest
      
      steps: 
            
      - name: install ssh keys
      
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    
      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.4.0 # Использовать github action, чтобы настроить ssh-agent
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} # Используйте ваш приватный ключ SSH

      - name: Clone repository
        run: ssh-add -L && git clone git@github.com:alexandrBally/BRAVO_DEVOPS.git
          
      
