on:
    push:
      branches:
        - main
    workflow_dispatch:
    
jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
            -   uses: actions/checkout@v1

            -   name: Setup SSH Keys and known_hosts
                env:
                    SSH_AUTH_SOCK: /tmp/ssh_agent.sock
                run: |
                    mkdir -p ~/.ssh
                    ssh-keyscan github.com >> ~/.ssh/known_hosts
                    ssh-agent -a $SSH_AUTH_SOCK > /dev/null
                    ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

            -   name: Some task that fetches dependencies
                env:
                    SSH_AUTH_SOCK: /tmp/ssh_agent.sock

            - name: connect and pull repo
              run:  |
               ssh bravo@18.116.3.154  "cd /home/bravo/BRAVO/BRAVO_FE && git clone git@github.com:alexandrBally/BRAVO_DEVOPS.git"
